# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
    )$

repos:

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black

  - repo: local
    hooks:
    - id: scss
      name: boussole
      types: [scss]
      language: python
      additional_dependencies: [boussole]
      entry: boussole compile --config=.boussole.json
      pass_filenames: false
